spring.application.name=Web-Tech-Projekt-1
spring.datasource.url=jdbc:postgresql://dpg-d8n85hmrnols73ddvau0-a.frankfurt-postgres.render.com/webtech_db_47q1
spring.datasource.username=webtech_db_47q1_user
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}